#%RAML 1.0 Library

types:
  rankedAbundancePostResponse:
    properties:
      data: 
        type: rankedAbundanceData # some data table with samples as rows
      appMetadata: rankedAbundanceMetadata[] # one per computation.
      stats: # none?

  rankedAbundanceMetadata:
    additionalProperties: false
    type: metadata
    properties:
      wasCutoff:
        type: string
        enum: ['TRUE', 'FALSE']

  alphaDivAppPostRespose:
    properties:
      data:
        type: alphaDivData # some data table with samples as rows
      appMetadata: 
        type: metadata[]
      stats: # none?

  betaDivAppPostResponse:
    properties: 
      data:
        type: betaDivData  # some data table with samples as rows
      appMetadata:
        type: metadata
      stats: betaDivStats[]

  betaDivStats:
    additionalProperties: false
    properties: 
      pcoaVariance: 
        type: number[]    # Ex. [0.5, 0.2, ...]

  metadata:
    properties:
      computedVariables:
        type: string[]    # Ex. ['shannon’]
      computedVariableLabels:
        type: string[]    # Ex. ['Shannon diversity']
        required: false
      computedAxisLabel: 
        type: string   # Ex. ‘Alpha Diversity’
        required: false
      defaultRange:
        type: number[]    # Ex. [0, 1]
        required: false
      computeDetails:
        type: string      # Ex. 'No convergence after 100 iterations' or ‘134 of 150 samples have sufficient data for this computation’
      computeName:
        type: string # Ex. 'median'
